# production environment
FROM node:16.15.0
# Create app directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
# Create env variables
ENV PATH /usr/src/app/node_modules/.bin:$PATH
ARG GENERATE_SOURCEMAP=${GENERATE_SOURCEMAP}
ENV GENERATE_SOURCEMAP=${GENERATE_SOURCEMAP}

ARG VITE_BACKEND_URL=${VITE_BACKEND_URL}
ENV VITE_BACKEND_URL=${VITE_BACKEND_URL}
ARG VITE_BACKEND=${VITE_BACKEND}
ENV VITE_BACKEND=${VITE_BACKEND}
ARG VITE_GATE_ROLL_SPEED=${VITE_GATE_ROLL_SPEED}
ENV VITE_GATE_ROLL_SPEED=${VITE_GATE_ROLL_SPEED}

ARG APP_PORT=${APP_PORT}
ENV APP_PORT=${APP_PORT}

ARG DB_HOST=${DB_HOST}
ENV DB_HOST=${DB_HOST}
ARG DB_USER=${DB_USER}
ENV DB_USER=${DB_USER}
ARG DB_PASSWORD=${DB_PASSWORD}
ENV DB_PASSWORD=${DB_PASSWORD}
ARG DB_NAME=${DB_NAME}
ENV DB_NAME=${DB_NAME}

ARG ACCESS_JWT_SAMESITE=${ACCESS_JWT_SAMESITE}
ENV ACCESS_JWT_SAMESITE=${ACCESS_JWT_SAMESITE}
ARG ACCESS_JWT_SECRET=${ACCESS_JWT_SECRET}
ENV ACCESS_JWT_SECRET=${ACCESS_JWT_SECRET}
ARG ACCESS_JWT_EXPIRESIN=${ACCESS_JWT_EXPIRESIN}
ENV ACCESS_JWT_EXPIRESIN=${ACCESS_JWT_EXPIRESIN}
ARG ACCESS_JWT_SECURE=${ACCESS_JWT_SECURE}
ENV ACCESS_JWT_SECURE=${ACCESS_JWT_SECURE}
ARG ACCESS_JWT_COOKIE_MAXAGE=${ACCESS_JWT_COOKIE_MAXAGE}
ENV ACCESS_JWT_COOKIE_MAXAGE=${ACCESS_JWT_COOKIE_MAXAGE}

ARG FRONTEND_URL=${FRONTEND_URL}
ENV FRONTEND_URL=${FRONTEND_URL}

ARG VITE_FRONTEND_SRC_URL=${VITE_FRONTEND_SRC_URL}
ENV VITE_FRONTEND_SRC_URL=${VITE_FRONTEND_SRC_URL}


COPY ./ /usr/src/app
RUN npm install -g pnpm
# Create front app
RUN cd ./frontend && pnpm i && pnpm build
RUN mkdir -p ./frontend/dist/src && cp -r ./frontend/src/assets ./frontend/dist/src
# Create back app
RUN cd ./backend && pnpm i --prod

# expose full app on APP_PORT
EXPOSE ${APP_PORT}
CMD ["node", "backend/index.js"]
