const symbols = [
  { id: 1, letter: "A", poi: [], label: "Earth" },
  { id: 2, letter: "B", poi: [], label: "Crater" },
  { id: 3, letter: "C", poi: [], label: "Virgo" },
  { id: 4, letter: "D", poi: [], label: "Bootes" },
  { id: 5, letter: "E", poi: [], label: "Centaurus" },
  { id: 6, letter: "F", poi: [], label: "Libra" },
  { id: 7, letter: "G", poi: [], label: "Serpens Caput" },
  { id: 8, letter: "H", poi: [], label: "Norma" },
  { id: 9, letter: "I", poi: [], label: "Scorpio" },
  { id: 10, letter: "J", poi: [], label: "Cra" },
  { id: 11, letter: "K", poi: [], label: "Scutum" },
  { id: 12, letter: "L", poi: [], label: "Sagittarius" },
  { id: 13, letter: "M", poi: [], label: "Aquila" },
  { id: 14, letter: "N", poi: [], label: "Mic" },
  { id: 15, letter: "O", poi: [], label: "Capricorn" },
  { id: 16, letter: "P", poi: [], label: "Pisces Austrinus" },
  { id: 17, letter: "Q", poi: [], label: "Equuleus" },
  { id: 18, letter: "R", poi: [], label: "Aquarius" },
  { id: 19, letter: "S", poi: [], label: "Pegasus" },
  { id: 20, letter: "T", poi: [], label: "Sculptor" },
  { id: 21, letter: "U", poi: [], label: "Pisces" },
  { id: 22, letter: "V", poi: [], label: "Andromeda" },
  { id: 23, letter: "W", poi: [], label: "Triangulum" },
  { id: 24, letter: "X", poi: [], label: "Aries" },
  { id: 25, letter: "Y", poi: [], label: "Perseus" },
  { id: 26, letter: "Z", poi: [], label: "Cetus" },
  { id: 27, letter: "a", poi: [], label: "Taurus" },
  { id: 28, letter: "b", poi: [], label: "Auriga" },
  { id: 29, letter: "c", poi: [], label: "Eridanus" },
  { id: 30, letter: "d", poi: [], label: "Orion" },
  { id: 31, letter: "e", poi: [], label: "Canis Minor" },
  { id: 32, letter: "f", poi: [], label: "Monoceros" },
  { id: 33, letter: "g", poi: [], label: "Gemini" },
  { id: 34, letter: "h", poi: [], label: "Hydra" },
  { id: 35, letter: "i", poi: [], label: "Lynx" },
  { id: 36, letter: "j", poi: [], label: "Cancer" },
  { id: 37, letter: "k", poi: [], label: "Sextans" },
  { id: 38, letter: "l", poi: [], label: "Leo Minor" },
  { id: 39, letter: "m", poi: [], label: "Leo" },
  { id: 40, letter: "n", poi: [], label: "Abydos" },
];

export default symbols;
