const symbols = [
  { id: 1, poi: [], label: "Earth" },
  { id: 2, poi: [], label: "Crater" },
  { id: 3, poi: [], label: "Virgo" },
  { id: 4, poi: [], label: "Bootes" },
  { id: 5, poi: [], label: "Centaurus" },
  { id: 6, poi: [], label: "Libra" },
  { id: 7, poi: [], label: "Serpens Caput" },
  { id: 8, poi: [], label: "Norma" },
  { id: 9, poi: [], label: "Scorpio" },
  { id: 10, poi: [], label: "Cra" },
  { id: 11, poi: [], label: "Scutum" },
  { id: 12, poi: [], label: "Sagittarius" },
  { id: 13, poi: [], label: "Aquila" },
  { id: 14, poi: [], label: "Mic" },
  { id: 15, poi: [], label: "Capricorn" },
  { id: 16, poi: [], label: "Pisces Austrinus" },
  { id: 17, poi: [], label: "Equuleus" },
  { id: 18, poi: [], label: "Aquarius" },
  { id: 19, poi: [], label: "Pegasus" },
  { id: 20, poi: [], label: "Sculptor" },
  { id: 21, poi: [], label: "Pisces" },
  { id: 22, poi: [], label: "Andromeda" },
  { id: 23, poi: [], label: "Triangulum" },
  { id: 24, poi: [], label: "Aries" },
  { id: 25, poi: [], label: "Perseus" },
  { id: 26, poi: [], label: "Cetus" },
  { id: 27, poi: [], label: "Taurus" },
  { id: 28, poi: [], label: "Auriga" },
  { id: 29, poi: [], label: "Eridanus" },
  { id: 30, poi: [], label: "Orion" },
  { id: 31, poi: [], label: "Canis Minor" },
  { id: 32, poi: [], label: "Monoceros" },
  { id: 33, poi: [], label: "Gemini" },
  { id: 34, poi: [], label: "Hydra" },
  { id: 35, poi: [], label: "Lynx" },
  { id: 36, poi: [], label: "Cancer" },
  { id: 37, poi: [], label: "Sextans" },
  { id: 38, poi: [], label: "Leo Minor" },
  { id: 39, poi: [], label: "Leo" },
];

export default symbols;
